version: '3.8'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
    networks:
      - backend_network

  todo:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime      
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "50051:50051" 
      - "8000:8000" 
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
