version: '3.8'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
    networks:
      - backend_network

  todo:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime        # make sure you’re using the final stage
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "50051:50051"   # gRPC
      - "8000:8000"     # HTTP (when you enable the gateway)
    networks:
      - backend_network
    # no command or entrypoint override here–it inherits:
    # ENTRYPOINT ["tail", "-f", "/dev/null"]
    # from your Dockerfile’s runtime stage

networks:
  backend_network:
    driver: bridge
